const lang = {
    hu: {
        aboutDesc: 'Magasszintű informatikai érdeklődésem miatt nem jelent problémát egy szoftver elsajátítása, legutóbbi munkahelyemen ahol 3 és fél évet dolgoztam szintén az ipari gépek programozását és adatbázisát kellet elsajátítanom. Autódidakta módon fejlesztem magam a programozás világában és az eddig megszerzett tudásommal úgy érzem hogy a cég nö vekedését támogathatom.',
        telekom: 'A vállalat által üzemeltetett töltőgépek össze és szétszerelése,a különböző termékekhez való beállítása HCU rendszerben,termékmozgások lekönyvelése SQL adatbázisban. A termelés nyomonkövetése a vállalat szervergépén,',
        handle: 'A vállalat által üzemeltetett töltőgépek össze és szétszerelése,a különböző termékekhez való beállítása HCU rendszerben,termékmozgások lekönyvelése SQL adatbázisban. A termelés nyomonkövetése a vállalat szervergépén, időszakos adatok lekönyvelése Excel formátumban. A füstölő kamrák feltöltése és beállítása. A megszerzett tapasztalatom és felelőségtudatom miatt több esetben műszakvezetőként is lehetőségem volt bizonyítani alkalmasságomat.',
        ms: 'A vállalat Európai központi elosztó raktárbázisában a feladataim közé tartozott a több ezres tételből álló beérkező árú könyvelése a cég által fejlesztett adatbázisban valamint a raktárrend fenntartása.',
        lidl: 'Bolti értékesítőként feladataim közé tartozott a vevők magasfokú, empatikus kiszolgálása, részükre információadás, reklamációk kezelése. Az áru folyamatos feltöltése, beérkező szállítmányok ellenőrzése, átvétele, a visszáru fogadása és a raktárrend fenntartása.',
        mercedes: 'Autóalkatrészek bevételezése, lekönyvelése Excel adatbázisban, raktározási feladatok ellátása, termékek csomagolása, szállítása, különös figyelemmel a gyártósorok megfelelő üzemeléséhez elengedhetetlen időhatárok betartására.',
        contact: 'kapcsolat',
        education: 'végzettség',
        language: 'nyelv',
        profile: 'rólam',
        experience: 'tapasztalat',
        interest: 'erdeklődés',
        telekomTitle: 'mainframe adminisztrátor',
        handleTitle: 'gépmester',
        msTitle: 'raktáros',
        lidlTitle: 'bolti dolgozó',
        mercedesTitle: 'logisztikai munkatárs',
        cook: 'szakács',
        graduation: 'érettségi',
        ger: 'német',
        eng: 'angol',
        au: 'ausztria',
        uk: 'anglia',
        ge: 'németország',
        gaming: 'játék',
        cooking: 'főzés'
    },
    en: {
        aboutDesc: 'Due to my high interest in IT, learning a software is not a problem, at my last workplace where I worked for 3 and a half years, I also had to learn the programming and database of industrial machines. I am developing myself in the world of programming in a self-taught way, and with the knowledge I have acquired so far, I feel that I can support the growth of the company.',
        telekom: "Assembling and disassembling the filling machines operated by the company, adjusting them for different products in the HCU system, recording product movements in an SQL database. Monitoring of production on the company's server machine",
        handle: "Assembling and disassembling the filling machines operated by the company, adjusting them for different products in the HCU system, recording product movements in an SQL database. Monitoring of production on the company's server machine, recording periodic data in Excel format. Filling and adjusting the smoking chambers. Due to my acquired experience and sense of responsibility, I had the opportunity to prove my suitability as a shift leader in several cases.",
        ms: 'In the European central distribution warehouse of the company, my tasks included the accounting of the incoming price of several thousand items in the database developed by the company and the maintenance of the warehouse order.',
        lidl: 'As a store salesperson, my duties included high-level, empathetic customer service, providing them with information, and handling complaints. Continuous replenishment of goods, checking and acceptance of incoming shipments, receiving returned goods and maintaining warehouse order.',
        mercedes: 'Receipt and recording of car parts in an Excel database, storage tasks, packaging and delivery of products, paying particular attention to meeting the deadlines essential for the proper operation of the production lines.',
        contact: 'contact',
        education: 'education',
        language: 'language',
        profile: 'profile',
        experience: 'experience',
        interest: 'interest',
        telekomTitle: 'mainframe administrator',
        handleTitle: 'machinist',
        msTitle: 'warehouseman',
        lidlTitle: 'shop worker',
        mercedesTitle: 'logistics associate',
        cook: 'cook',
        graduation: 'education',
        ger: 'german',
        eng: 'english',
        au: 'austria',
        uk: 'united kingdom',
        ge: 'germany',
        gaming: 'gaming',
        cooking: 'cooking'
    }
}

